### ISSUE TITLE
If have preposition in description, task will be buggy

### ISSUE THREAD

**Issue by chuajiaxuan** [cs2103jan2016-f14-1j/main#100]
e.g. "man on moon meeting with NASA"

**Comment by ohsyln** [comment]
no problem leh, can double-confirm exact commands that fail? @chuajiaxuan

**Comment by chuajiaxuan** [comment]
Oh! Paiseh wrong example! exact command is this "add Trip to Korea from 27May to 5Jun". It will come out as "Trip to Korea from Korea 27May - 27May to 05Jun"

**Comment by ohsyln** [comment]
might have introduced other bugs
