### ISSUE TITLE
BUG: editing date and time range causes task name to change

### ISSUE THREAD

**Issue by ohsyln** [cs2103jan2016-f14-1j/main#104]
e.g.
- (1) buy chicken

after executing "edit 1 to 9apr from 1pm to 5pm" it becomes
- (1) 9 apr - 9apr (1pm - 5pm)

instead of
- (1) buy chicken - 9Apr (1pm - 5pm)

**Comment by ohsyln** [comment]
GG don't understand the edit function logic @jmtiong

**Comment by jmtiong** [comment]
@sylnsyln it is @ymymym! but wait i solving it now
