### ISSUE TITLE
As a user, I can display tasks sorted by deadline

### ISSUE THREAD

**Issue by ohsyln** [cs2103jan2016-f14-1j/main#17]
so that I know what tasks needs to be completed soon

**Comment by chuajiaxuan** [comment]
What happens when we sort with task without dateline? do the dateline-less tasks not get displayed? Or do they always appear below those with datelines? e.g. [most urgent to least urgent vice versa] then [dateline-less]? TBD

**UPDATE:** Basic sorting by natural ordering is up.

**Comment by chuajiaxuan** [comment]
**UPDATE!** Now is auto sort by deadline (those more urgent first) No longer need this.
