### ISSUE TITLE
test edit command for #3

### ISSUE THREAD

**Issue by jmtiong** [cs2103jan2016-f14-1j/main#42]
#3

**Comment by chuajiaxuan** [comment]
**BUG!!!!!** Program crashed or exited when user types "edit" alone with nothing else. This happens with "add", "do" and "delete" as well!

Error Message shown below:
![bug2](https://cloud.githubusercontent.com/assets/16714478/13198967/28b4a958-d852-11e5-9fc0-63fc5bff3d6e.png)

**UPDATE:** I managed to solve the bug!

**Comment by chuajiaxuan** [comment]
When keying in edit <TaskID#> <String>, without the "to" word, date of task gets removed.

**RESOLVED**

**Comment by chuajiaxuan** [comment]
Question: When keying in "edit <taskID> to This thursday", date becomes "Thisthursday" instead of "This thursday". Should it be this way? Examples:
"edit 4 to 2feb" --> (taskID) (Task Description) - 02feb
"edit 4 to 2 feb" --> (taskID)  (Task Description) - 02feb

**ANSWERED**

**Comment by ohsyln** [comment]
for now, we work with legit dates first (assume user input)
ignore the day input (thur, fri)
