### ISSUE TITLE
Test GUI view, success and fail messages

### ISSUE THREAD

**Issue by chuajiaxuan** [cs2103jan2016-f14-1j/main#47]
#19

**Comment by chuajiaxuan** [comment]
When command fails, it show success! Hahah

**UPDATE**: now working for all commands except view (category/invalid text). e.g view RAWR shows default view and command success when it should show command fail

**Comment by jmtiong** [comment]
for the view command, we have met the objectives for v0.0 which is only to show completed and not completed tasks.

This will be carried forward to the next version for improvement.
