### ISSUE TITLE
Test simple add function

### ISSUE THREAD

**Issue by chuajiaxuan** [cs2103jan2016-f14-1j/main#48]
#2

**Comment by chuajiaxuan** [comment]
BUG!!! Regeneration of SAME TASKID! ALERT ALERT! When initialise program, first task assigned to 457, after adding two tasks suddenly 3rd task also assigned 457. I believe the first task was supposed to be 455.
![bug1](https://cloud.githubusercontent.com/assets/16714478/13198876/c4bd1c2a-d84f-11e5-84c2-cb3568510562.png)

**Comment by chuajiaxuan** [comment]
Are we allowed to add a task with same task description?

**RESOLVED** See comment below

**Comment by ymymym** [comment]
we should be able to add task with same description. unless u guys wanna implement a task can have multiple dates

**Comment by ohsyln** [comment]
same description ok, but same ID should NEVER happen
probably a bug in the taskID generator

**Comment by jmtiong** [comment]
Bug fixed. See latest commit for change
