### ISSUE TITLE
As a user, I can delete unwanted tasks

### ISSUE THREAD

**Issue by ohsyln** [cs2103jan2016-f14-1j/main#5]
so I can remove them from the todo list

**Comment by ohsyln** [comment]
essentially same as 'doing' a task..

**Comment by jmtiong** [comment]
this will lead to whether or not we would want to allow the users to view his completed tasks or not

**Comment by chuajiaxuan** [comment]
Currently working, but only deleting by order of tasks, not taskID.

**Comment by chuajiaxuan** [comment]
deleteTask is officially working! Woohoo!
