### ISSUE TITLE
"add buy chicken #thanksgiving at 13 mar at 4pm" screws up date

### ISSUE THREAD

**Issue by ohsyln** [cs2103jan2016-f14-1j/main#67]
PrettyTimeParser detects "thanksgiving" as a legit date

**Comment by ohsyln** [comment]
prettytimeparser GG-fied wtfz

**Comment by chuajiaxuan** [comment]
Should we try editing the pretty time parser file?? https://github.com/ocpsoft/prettytime/blob/master/nlp/src/main/java/org/ocpsoft/prettytime/nlp/PrettyTimeParser.java @ymymym @sylnsyln @jmtiong

**Comment by ohsyln** [comment]
solved
