### ISSUE TITLE
Exception handling for invalid input

### ISSUE THREAD

**Issue by jmtiong** [cs2103jan2016-f14-1j/main#68]

**Comment by chuajiaxuan** [comment]
Jm, for this is it handle both invalid command (e.g. "ads", "kill" etc) and invalid after-command words (e.g "add ", "delete asdfsdgafa") ???? I dont quite understand what is the invalid input you mean. XD

**Comment by jmtiong** [comment]
yupyup you are right as well as things like

e.g. delete 111 3929 0000 where these numbers does not exists
edit 9999 to weoraoi where 9999 does not exists
do 12839 where it does not exists
