### ISSUE TITLE
REFINE: buggy if task name contains keywords (prepositions)

### ISSUE THREAD

**Issue by ohsyln** [cs2103jan2016-f14-1j/main#77]
e.g. add man on moon with NASA on 24 mar
"on" is a preposition

**Comment by jmtiong** [comment]
E.g.

add interview with man on the moon on 24 march
add interview from home on 24 mar 3pm
add buy eggs on internet on 24 mar
add buy items by the bay by 13 mar
add buy hamburger on eggs with mom groceries on 23 mar

**Comment by ymymym** [comment]
this is also for edit function.

**Comment by ohsyln** [comment]
solved for:
add interview with man on the moon on 24 march
add buy eggs on internet on 24 mar
add buy items by the bay by 13 mar
add buy hamburger on eggs with mom groceries on 23 mar

fails:
add interview from home on 24 mar 3pm (because no preposition between "24 mar" and "3pm")
