### ISSUE TITLE
Cannot change non-floating task to floating task

### ISSUE THREAD

**Issue by chuajiaxuan** [cs2103jan2016-f14-1j/main#99]
I dont know if this is a need?

**Comment by ohsyln** [comment]
need or not ah, discuss pls

**Comment by chuajiaxuan** [comment]
I think is a need. Cause just now when I wanted to edit a task, i wrongly edited the wrong floating task with the date then cannot change back. BUT this could be solved with the undo command. HOWEVER, the undo command not working for edit I think. so if undo command can handle this, i think can join the two bugs together!

**Comment by jmtiong** [comment]
undo can change back the state of the task previously. Hence I shall close it
